### ISSUE TITLE
react-redux performance fixes

### ISSUE THREAD

**Issue by crobinson42** [salvoravida/react-redux-fork#1]
Just want to reference this for tracking :-) I'm using this _fork_ because I needed the performance in a large app.. but I'd like to converge back to the original package since that's where all the support is.

https://github.com/reduxjs/react-redux/issues/1177

**Comment by salvoravida** [comment]
Thank you for testing it. you will get support even here :D

**Comment by crobinson42** [comment]
@salvoravida curious what's your vision for this project/fork? Do you plan on improving or just staying parallel?

**Comment by salvoravida** [comment]
Sadly RR manteiners are not very "opened" to open-source project and they think that only their magic-circle team can express right/wrong architecture/vision.

That said, i decided to fork officially the project because too many real-world-large apps are suffering from many months about their wrong vision of React Context. 

Yes i'm planning to continue with new Api, and a "turbo mode" that will not use ReactContext at all. Stay tuned :D
